```{r}
install.packages("gganimate")
library(gganimate)
library(tidyverse)
library(dplyr)
library(gifski)
library(rnaturalearth)
library(transformr)
library(png)
library(rnaturalearthdata)
library(gganimate)
```

```{r}
owid_co2_data<- read_csv("../data/owid-co2-data.csv")
```

```{r}
CO2_data <- owid_co2_data
```


```{r}
Our_co2_dataset <- owid_co2_data %>% 
  select("country", "year", "population", "co2", "co2_per_capita", "iso_code")
```

```{r}
world <- ne_countries(scale = "medium", returnclass = "sf")
class(world)

## [1] "sf"  
## [1] "data.frame"
```

```{r}
names(world)[10] <- "iso_code"


all_countries <- Our_co2_dataset %>%
  expand(iso_code, year)


CO2_complete <- left_join(all_countries, Our_co2_dataset, by = c("iso_code", "year"))
```


```{r}
merged_data <- full_join(world, CO2_complete, by = c("iso_code"))
```



```{r}
merged_data %>% 
  filter(year == 2020) %>% 
ggplot(aes(fill = co2_per_capita)) +
    geom_sf() +
  scale_fill_gradient(low = "blue", high ="red") +
  theme_void()
  #transition_time(year)
  #transition_reveal(time = year)
```
```{r}
mini <- merged_data %>%
  filter(year %in% c(2020, 2019, 2018, 2017, 2016))

anim <- ggplot() +
  geom_sf(data = mini, aes(fill = co2_per_capita, group = year)) +
  scale_fill_gradient(low = "blue", high = "red") +
  theme_void() +
  transition_states(year) +
  labs(title = "Year: {closest_state}")
```

```{r}
animate(anim, renderer = gifski_renderer())
anim_save("anim.gif", anim, path = NULL)
```

```{r}
my_map <- ggplot() +
  geom_sf(data = merged_data, aes(fill = co2)) +
  scale_fill_gradient(low = "blue", high = "red") +
  theme_void()
```

```{r}
my_anim_map <- my_map +
  transition_time(year) +
  labs(title = "Year: {frame_time}")
```

```{r}
#anim_save("my_animation.gif", my_anim_map)
```


```{r}
minismall <- CO2_complete %>%
  filter(year %in% c(2020, 2019, 2018, 2017, 2016)) %>% 
  write.csv("tiny.csv")
```
