```{r load-packages, message = FALSE}
library(tidyverse)
library(broom)
library(readr)
```

```{r read-in-csv}
owid_co2_data <- read_csv("owid-co2-data.csv")
```

```{r focus-on-post-1949}
owid_co2_data %>%
          group_by(country) %>%
          filter(year > "1949") %>%
     select( country)
```

```{r focus-on-us-and-china}
owid_co2_data %>%
  mutate(example_countries <- "United Sates, China")
```
```{r co2-line-plot}
     ggplot(owid_co2_data, aes(x= year, y=co2, color=country)) +
     geom_line() +
       xlim(1950, 2021)
```
```{r create-our-dataset}
Our_co2_dataset <- owid_co2_data %>%
   select("country", "year", "population", "co2", "co2_per_capita")
```
```{r glimpse-our-dataset}
glimpse(Our_co2_dataset)
```


# data

This dataset is pulled from ourworldindata.org/co2-and-greenhouse-gas-emissions
Dimensions: 46,523 observations and 74 variables

## owid-co2-data

Full codebook can be found in the data folder under owid-co2-codebook.csv

```{r glimpse-dataset}
glimpse(owid_co2_data)
```

